{% set name = "opentelemetry-instrumentation-botocore" %}
{% set version = "0.25b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-botocore-{{ version }}.tar.gz
  sha256: d29184f364c6ce56442f39967437aac950a558e3451832543b527bacd815adc7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b0
    - opentelemetry-semantic-conventions ==0.25b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - moto ~=2.0
    # - botocore ~=1.0
    # - opentelemetry-test ==0.25b0
    # - moto ~=2.0
    # - botocore ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-botocore
  summary: OpenTelemetry Botocore instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
