{% set name = "opentelemetry-instrumentation-botocore" %}
{% set version = "0.33b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-botocore-{{ version }}.tar.gz
  sha256: 61a6bc2c13ba22cb44a3f756440359066886a93511498421ff032b2811fa188e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.33b0
    - opentelemetry-semantic-conventions ==0.33b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - moto ~=2.0
    # - botocore ~=1.0
    # - opentelemetry-test ==0.25b0
    # - moto ~=2.0
    # - botocore ~=1.0
    # - opentelemetry-test ==0.25b2
    # - moto ~=2.2.6
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.26b1
    # - moto ~=2.2.6
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.27b0
    # - moto ~=2.2.6
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.28b1
    # - moto ~=2.2.6
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.29b0
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.30b0
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.30b1
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.31b0
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.32b0
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0
    # - opentelemetry-test-utils ==0.33b0
    # - moto ~=2.2.6
    # - markupsafe ==2.0.1
    # - botocore ~=1.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-botocore
  summary: OpenTelemetry Botocore instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
